from python:3.10
RUN pip install uv
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen
COPY . .
EXPOSE 8000
CMD ["uv", "run","backend/pipeline/db_init.py","backend/pipeline/db_update.py"]




