FROM python:3.10
RUN pip install uv
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen
COPY . .
CMD ["uv", "run", "uvicorn", "backend.api.api:app", "--host", "0.0.0.0", "--port", "$PORT"]




