[project]
name = "earthquakes-service"
version = "0.1.0"
description = "API for visualizing earthquake data on an interactive map."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.135.1",
    "psycopg[binary]>=3.3.3",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "streamlit>=1.55.0",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
    "mypy>=1.20.0",
    "pandas-stubs>=2.3.3.260113",
    "pylint>=4.0.5",
    "types-pyyaml>=6.0.12.20260408",
    "types-requests>=2.33.0.20260402",
]
