[project]
name = "earthquakes-service"
version = "0.1.0"
description = "API for visualizing earthquake data on an interactive map."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.135.1",
    "psycopg[binary]>=3.3.3",
    "requests>=2.32.5",
    "streamlit>=1.55.0",
]
